Refactor & Core metrics implementation
GoogleCloudPlatform/k8s-stackdriver pull request #371
Opened 2020-08-25 13:25 UTC by znirzej

There are three commits, the first two should be easy to review because it's mainly refactoring.

Split translator file, move translator initialization to main adapter file
Split provider package into provider and translator packages
Core metrics functionality

2020-08-25 13:46 UTC, znirzej commented
@kawych @serathius @cezarygerard

2020-09-02 00:51 UTC, cezarygerard requested changes

2020-09-02 00:51 UTC, cezarygerard commented on custom-metrics-stackdriver-adapter/adapter.go
> +type clock interface {
You don't need clock and realClock  structs here. 
declare them in query_builder.go

2020-09-02 00:51 UTC, cezarygerard commented on custom-metrics-stackdriver-adapter/pkg/adapter/provider/query_builder.go
> +		clock:               c,
you dont need 'c' arg in this methos
simply assign a real clock to clock fields
kin tests you can replace   clock field with fake clock

what is the rationale for this change? Maybe I don't get something.

2020-09-02 00:51 UTC, cezarygerard commented on custom-metrics-stackdriver-adapter/pkg/adapter/provider/translator_test_utilities.go
> +Copyright 2017 The Kubernetes Authors.
rename this file to translator_test_utils.go

2020-09-02 00:51 UTC, cezarygerard commented on custom-metrics-stackdriver-adapter/pkg/adapter/translator/query_builder.go
> +	MaxNumOfArgsInOneOfMax = 100
it would be more readable to name it MaxNumOfArgsInOneOfFilter

2020-09-02 00:51 UTC, cezarygerard commented on custom-metrics-stackdriver-adapter/pkg/adapter/provider/provider.go
> +			podsSlice := &v1.PodList{Items: matchingPods.Items[i:min(i+translator.MaxNumOfArgsInOneOfMax, len(matchingPods.Items))]}
can you split this line? There are 3 or 4 things goin on in the same line

2020-09-02 00:53 UTC, cezarygerard requested changes
can you separate refactor and implementation into different PRs?

2020-09-02 16:00 UTC, cezarygerard approved these changes

2020-09-02 16:01 UTC, merged